### ISSUE TITLE
Simplifying commands with trigger from another bot

### ISSUE THREAD

**Issue by YT-SimplyMe** [Tdortiz/PUBG-Discord-Bot#10]
Hi,

at first thanks a lot for your work.

I am using the PUBG-Discord-Bot as well as Nightbot on my Discord server.
Now I am trying to simplify the PUBG-Bots commands by adding a trigger command to Nightbot, f.e.

PUBG-Bot
!pubg-top 5 season=2018-04 region=eu squadSize=1 mode=fpp

Nightbot trigger which should fire up the PUBG-Bot command:
!top5

But it seems, that the PUBG-Bot does not listen to other bots inputs. Is there any way to activate listening?
If not, could you implement custom commands and aliases to the PUBG-Discord-Bot, comparable to this?
https://docs.nightbot.tv/commands/commands

**Comment by Tdortiz** [comment]
@YT-SimplyMe With the most recent update you should be able to do this now :)
